server:
  port: 8070
  servlet:
    context-path: /

spring:
  application:
    name: iam
  datasource:
    driver-pass-name: org.postgresql.Driver
    #    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5432/DOUBLEDI_IAM?currentSchema=DOUBLEDI_IAM&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 1m
  cache:
    redis:
      time-to-live: 1m
    custom-cache:
      user-authority: 1m
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
