server:
  port: 8070
  servlet:
    context-path: /

spring:
  application:
    name: iam
  datasource:
    driver-pass-name: org.postgresql.Driver
    #    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5432/DOUBLEDI_IAM?currentSchema=DOUBLEDI_IAM&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 1m
  cache:
    redis:
      time-to-live: 1m
    custom-cache:
      user-authority: 1m
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  messages:
    always-use-message-format: true
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: true

cloud:
  aws:
    credentials:
      access-key: AKIARJJ2LLOKROLHWY7U
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: cinema-storage
logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error
